apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "password" # 设置 root 用户密码
        volumeMounts:
        - name: mysql-init
          mountPath: /docker-entrypoint-initdb.d
        resources:
          requests:
            memory: "128Mi"  # 容器启动所需的最低内存
            cpu: "250m"      # 容器启动所需的最低 CPU
          limits:
            memory: "512Mi"  # 容器最多可以使用的内存
            cpu: "500m"      # 容器最多可以使用的 CPU
      volumes:
      - name: mysql-init
        hostPath:
          path: /root/mysql/init


---

apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nacos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nacos
  template:
    metadata:
      labels:
        app: nacos
    spec:
      containers:
      - name: nacos
        image: nacos/nacos-server:v2.1.0-slim
        ports:
        - containerPort: 8848
        - containerPort: 9848
        - containerPort: 9849
        env:
        - name: MODE
          value: "standalone"
        - name: PREFER_HOST_MODE
          value: "hostname"
        - name: NACOS_SERVER_PORT
          value: "8848"
        - name: MYSQL_SERVICE_HOST
          value: "mysql-service"
        - name: MYSQL_SERVICE_PORT
          value: "3306"
        - name: MYSQL_SERVICE_DB_NAME
          value: "nacos"
        - name: MYSQL_SERVICE_USER
          value: "root"
        - name: MYSQL_SERVICE_PASSWORD
          value: "password"
        args:
        - "start"
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "16Gi"
            cpu: "1"

---

apiVersion: v1
kind: Service
metadata:
  name: nacos-service
spec:
  selector:
    app: nacos
  ports:
    - name: http
      port: 8848
      targetPort: 8848
    - name: tcp-metrics
      port: 9848
      targetPort: 9848
    - name: tcp-raft
      port: 9849
      targetPort: 9849
  type: ClusterIP
