apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.14
          ports:
            - containerPort: 18080
            - containerPort: 18081
          volumeMounts:
            - name: html-volume
              mountPath: /etc/nginx/html
            - name: nginx-config-volume
              mountPath: /etc/nginx/nginx.conf
          resources:
            requests:
              memory: "128Mi"  # 容器启动所需的最低内存
              cpu: "250m"      # 容器启动所需的最低 CPU
            limits:
              memory: "512Mi"  # 容器最多可以使用的内存
              cpu: "500m"      # 容器最多可以使用的 CPU
      volumes:
        - name: html-volume
          hostPath:
            path: /root/nginx/html
        - name: nginx-config-volume
          hostPath:
            path: /root/nginx/nginx.conf
      
---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - name: http
      protocol: TCP
      port: 18080         # Service 暴露的端口
      targetPort: 18080   # Pod 中的端口
    - name: admin
      protocol: TCP
      port: 18081
      targetPort: 18081
  type: ClusterIP          # 允许通过节点的 IP 和端口访问
