apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: tanyuzhentyz/hm-gateway:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "128Mi"  # 容器启动所需的最低内存
              cpu: "250m"      # 容器启动所需的最低 CPU
            limits:
              memory: "512Mi"  # 容器最多可以使用的内存
              cpu: "500m"      # 容器最多可以使用的 CPU
      
---

apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  selector:
    app: gateway
  ports:
    - protocol: TCP
      port: 8080         # Service 暴露的端口
      targetPort: 8080   # Pod 中的端口
  type: ClusterIP          # 允许通过节点的 IP 和端口访问
