server:
  port: 8084
spring:
  profiles:
    active: dev

hm:
  swagger:
    title: 黑马商城用户接口文档
    description: 黑马商城用户接口文档
    package: com.hmall.user.controller
  jwt:
    location: classpath:hmall.jks
    alias: hmall
    password: hmall123
    tokenTTL: 30m