server:
  port: 8082
spring:
  profiles:
    active: dev
  cloud:
    sentinel:
      transport:
        dashboard: 192.168.203.132:8858 #sentinel的控制台地址
      http-method-specify: true #开启Sentinel对http请求方式的支持
feign:
  okhttp:
    enabled: true
  sentinel:
    enabled: true #开启Sentinel对Feign的支持，可以在Feign调用中实现限流、熔断等功能


hm:
  swagger:
    title: 黑马商城购物车接口文档
    description: 黑马商城购物车接口文档
    package: com.hmall.cart.controller
