server:
  port: 8080
spring:
  application:
    name: gateway
  datasource:
    url: jdbc:h2:mem:testdb
    username: weng
    password: wengyehao123
  cloud:
    nacos:
      server-addr: 192.168.203.132
#   todo 动态路由
    gateway:
      routes:
        - id: item-service # 路由的id，没有规定规则但要求唯一，建议配合服务名（spring.application.name）
          uri: lb://item-service # 路由微服务的目标，从注册中心获取服务列表，lb表示负载均衡。
          predicates: # 路由断言（规则），判断请求是否符合规则，如果符合机路由到uri里写的目标
            - Path=/items/**,/search/** # 以请求路径做判断，以/items开头则符合
          # 192.168.203.132:8080/items/** => 192.168.203.132:8081/items/** 或 192.168.203.132:8083/items/**
          filters:
            - AddRequestHeader=name, husiqi
        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=/carts/**
        - id: pay-service
          uri: lb://pay-service
          predicates:
            - Path=/pay-orders/**
        - id: trade-service
          uri: lb://trade-service
          predicates:
            - Path=/orders/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**,/addresses/**
logging:
  level:
    org.springframework.cloud.gateway: debug

hm:
  jwt:
    location: classpath:hmall.jks
    alias: hmall
    password: hmall123
    tokenTTL: 30m
  auth:
    excludePaths:
      - /search/**
      - /users/login
      - /items/**
      - /hi


#      default-filters:
#        - AddRequestHeader=name, husiqi